UnityWeb/Models/Document/DocumentStatusViewModel.cs
namespace UnityWeb.Models.Document
{
  public class DocumentStatusViewModel
  {
    public DocumentStatusViewModel()
    {
    }

    public DocumentStatusViewModel(Entities.Document document)
    {
      if (document.GridRun != null)
      {
        Arrived = document.GridRun.XmlFile.Received.ToString("ddd d MMM yyyy HH:mm");
        Proccessed = document.GridRun.EndDate.GetValueOrDefault().ToString("ddd d MMM yyyy HH:mm");
      }

      if (document.Approval != null)
      {
        Approved = document.Approval.ApprovedDate.GetValueOrDefault().ToString("ddd d MMM yyyy HH:mm");
        ApprovedBy = document.Approval.ApprovedBy;
      }

      if (document.Rejection != null)
      {
        Rejected = document.Rejection.RejectionDate.GetValueOrDefault().ToString("ddd d MMM yyyy HH:mm");
        RejectedBy = document.Rejection.RejectedBy;
      }

      if (document.HouseHold != null)
      {
        HouseHeld = document.HouseHold.HouseHoldDate.GetValueOrDefault().ToString("ddd d MMM yyyy HH:mm");
      }
    }

    public string Arrived { get; set; }

    public string Proccessed { get; set; }

    public string Approved { get; set; }

    public string ApprovedBy { get; set; }

    public string Rejected { get; set; }

    public string RejectedBy { get; set; }

    public string Faxed { get; set; }

    public string Emailed { get; set; }

    public string HouseHeld { get; set; }
  }
}

UnityWeb/Controllers/CartItemController.cs
namespace UnityWeb.Controllers
{
  using System.Collections.Generic;
  using System.Linq;
  using System.Web.Mvc;
  using Entities;
  using Exceptions;
  using Logging;
  using ServiceInterfaces;
  using UnityWeb.Filters;
  using UnityWeb.Models.CartItem;

  [AuthorizeLoggedInUser]
  public class CartItemController : BaseController
  {
    private ICartItemService _cartItemService;
    private IExportFileService _exportFileService;
    private IDocumentService _documentService;

    public int PageSize = 10;

    public CartItemController(
        ICartItemService cartItemService,
        IExportFileService exportFileService,
        IDocumentService documentService,
        ILogger logger)
      : base(logger)
    {
      _cartItemService = cartItemService;
      _exportFileService = exportFileService;
      _documentService = documentService;
    }

    [AuthorizeLoggedInUser(Roles = "Admin,dstadmin,Governor")]
    public ActionResult Index(int page = 1, bool isAjaxCall = false)
    {
      var cartItemsViewModel = new CartItemsViewModel();
      CartItem cartItem = new CartItem(this.HttpContext);

      var cartItems = _cartItemService.GetCartItems(cartItem.CartId, page, PageSize);

      cartItemsViewModel.AddCartItems(cartItems);

      if (isAjaxCall)
      {
        return PartialView("_PagedCartItemResults", cartItemsViewModel);
      }

      if (cartItemsViewModel.CartTotal == 0)
      {
        return RedirectToAction("Index", "Dashboard");
      }

      return View(cartItemsViewModel);
    }

    public ActionResult AddGridToCart(string grid)
    {
      var checkedOutDoc = new List<string>();
      var couldNotAddDoc = new List<string>();
      var anotherManCoAlredy = new List<string>();

      var documents = _documentService.GetDocuments(grid);

      foreach (var document in documents)
      {
        this.AddDocumentToCart(document.DocumentId, document.ManCo.Code, document.DocType.Code, document.SubDocType.Code, anotherManCoAlredy, checkedOutDoc, couldNotAddDoc);
      }

      var cartItemSummaryViewModel = GetCartSummary();
      cartItemSummaryViewModel.DocumentWarningsViewModel.DocumentsAlreadyCheckedOut = string.Join(",", checkedOutDoc.ToArray());
      cartItemSummaryViewModel.DocumentWarningsViewModel.DocumentAddToBasketErrors = string.Join(",", couldNotAddDoc.ToArray());
      cartItemSummaryViewModel.DocumentWarningsViewModel.BasketContainsDocumentFromAnotherManCo = string.Join(",", anotherManCoAlredy.ToArray());

      return PartialView("_CartSummary", cartItemSummaryViewModel);
    }


    [HttpPost]
    public ActionResult AddToCart(AddCartItemsViewModel addCartItemsViewModel)
    {
      var checkedOutDoc = new List<string>();
      var couldNotAddDoc = new List<string>();
      var anotherManCoAlredy = new List<string>();

      if (addCartItemsViewModel.AddCartItemViewModel == null)
        return PartialView("_CartSummary", new CartItemSummaryViewModel());

      foreach (var document in addCartItemsViewModel.AddCartItemViewModel.Where(d => d.Selected))
      {
        this.AddDocumentToCart(document.DocumentId, document.ManCo, document.DocType, document.SubDocType, anotherManCoAlredy, checkedOutDoc, couldNotAddDoc);
      }

      var cartItemSummaryViewModel = GetCartSummary();
      cartItemSummaryViewModel.DocumentWarningsViewModel.DocumentsAlreadyCheckedOut = string.Join(",", checkedOutDoc.ToArray());
      cartItemSummaryViewModel.DocumentWarningsViewModel.DocumentAddToBasketErrors = string.Join(",", couldNotAddDoc.ToArray());
      cartItemSummaryViewModel.DocumentWarningsViewModel.BasketContainsDocumentFromAnotherManCo = string.Join(",", anotherManCoAlredy.ToArray());

      return PartialView("_CartSummary", cartItemSummaryViewModel);
    }

    private void AddDocumentToCart(
      string documentId, string manCo, string docType, string subDocType, List<string> anotherManCoAlredy, List<string> checkedOutDoc, List<string> couldNotAddDoc)
    {
      CartItem cartItem = new CartItem(this.HttpContext);

      try
      {
        this._cartItemService.AddItem(
          this.HttpContext.User.Identity.Name,
          documentId,
          cartItem.CartId,
          manCo,
          docType,
          subDocType);
      }
      catch (BasketContainsDifferentManCoException e)
      {
        anotherManCoAlredy.Add(documentId);
      }
      catch (DocumentCurrentlyCheckedOutException e)
      {
        checkedOutDoc.Add(documentId);
      }
      catch (UnityException e)
      {
        couldNotAddDoc.Add(documentId);
      }
    }

    [HttpPost]
    public ActionResult RemoveFromCart(RemoveCartItemsViewModel removeCartItemsViewModel)
    {
      foreach (var document in removeCartItemsViewModel.RemoveCartItemViewModel.Where(d => d.Selected))
      {
        CartItem cartItem = new CartItem(HttpContext);

        _cartItemService.RemoveItem(document.DocumentId, cartItem.CartId);
      }

      var cartItemSummaryViewModel = GetCartSummary();

      return PartialView("_CartSummary", cartItemSummaryViewModel);
    }

    public ActionResult ClearCart()
    {
      CartItem cartItem = new CartItem(HttpContext);
      _cartItemService.ClearCart(cartItem.CartId);

      return RedirectToAction("Index", "Dashboard");
    }

    [HttpPost]
    public ActionResult ExportBasketToZip(string cartId)
    {
      var cartItems = _cartItemService.GetCart(cartId);

      var documentIds = (from c in cartItems select c.Document.DocumentId).ToList();

      var zipFilePath = this._exportFileService.ExportToZip(documentIds);

      documentIds.ForEach(x => this._cartItemService.RemoveItem(x, cartId));

      return this.Json(new { file = zipFilePath });
    }

    [HttpPost]
    public ActionResult ExportDocumentsToZip(List<string> documentIds)
    {
      var zipFilePath = this._exportFileService.ExportToZip(documentIds);

      CartItem cartItem = new CartItem(HttpContext);

      documentIds.ForEach(x => this._cartItemService.RemoveItem(x, cartItem.CartId));

      return this.Json(new { file = zipFilePath });
    }

    public ActionResult Download(string file)
    {
      return this.File(file, System.Net.Mime.MediaTypeNames.Application.Zip, "ZippedDocuments.zip");
    }

    [ChildActionOnly]
    public ActionResult Summary()
    {
      var cartItemSummaryViewModel = GetCartSummary();
      return PartialView("_CartSummary", cartItemSummaryViewModel);
    }

    private CartItemSummaryViewModel GetCartSummary()
    {
      string cartId = new CartItem(HttpContext).CartId;
      int cartItems = _cartItemService.GetNumberOfItemsInCart(cartId);

      CartItemSummaryViewModel cartItemSummaryViewModel = new CartItemSummaryViewModel(cartItems);
      return cartItemSummaryViewModel;
    }
  }
}

UnityWeb/Controllers/DocumentController.cs
namespace UnityWeb.Controllers
{
  using System.Collections.Generic;
  using System.IO;
  using System.Linq;
  using System.Web.Mvc;
  using ClientProxies.ArchiveServiceReference;
  using Entities;
  using Logging;
  using ServiceInterfaces;
  using UnityWeb.Filters;
  using UnityWeb.Models.Document;
  using UnityWeb.Models.Search;

  [AuthorizeLoggedInUser]
  public class DocumentController : BaseController
  {
    private readonly IDocumentService _documentService;
    private readonly IUserService _userService;
    private readonly IManCoService _manCoService;
    private readonly int _pageSize = 10;

    public DocumentController(
        IDocumentService documentService, 
        IUserService userService,
        IManCoService manCoService,
        ILogger logger)
      : base(logger)
    {
      _documentService = documentService;
      _userService = userService;
      _manCoService = manCoService;
    }

    [HttpGet]
    public ActionResult Index()
    {
      var model = new DocumentsViewModel();

      TempData["valid"] = "Show filter";
      return View("Search", model);
    }
    
    public ActionResult SearchGrid(string grid, int page = 1, bool isAjaxCall = false, bool filterHouseHolding = false, bool filterUnapproved = false, bool filterApproved = false)
    {
      var documentsViewModel = new DocumentsViewModel(grid, filterHouseHolding);
      PagedResult<IndexedDocumentData> documents = _documentService.GetDocuments(page, _pageSize, grid, filterHouseHolding, filterUnapproved, filterApproved);
      documentsViewModel.AddDocuments(documents);
      ProcessDocumentResults(documentsViewModel);

      documentsViewModel.AddTotalDocs(_documentService.GetDocuments(grid).Count());
      documentsViewModel.AddDocsAwaitingApproval(_documentService.GetUnApprovedDocuments(grid).Count());
      documentsViewModel.AddDocsApproved(_documentService.GetApprovedDocuments(grid).Count());

      if (isAjaxCall)
      {
        return PartialView("_PagedDocumentResults", documentsViewModel);
      }

      return View("Search", documentsViewModel);
    }

    public ActionResult Show(string documentId)
    {
      byte[] document = _documentService.GetDocumentStream(documentId);
      var memoryStream = ConvertToStream(document);
      return File(memoryStream, "application/pdf");
    }
    
    public ActionResult Search(SearchViewModel SearchViewModel, int page = 1, bool isAjaxCall = false)
    {
      Session["SearchViewModel"] = null;

      if (!ModelState.IsValid)
      {
        var errorList = ModelState.Values.SelectMany(x => x.Errors).ToList();
        TempData["error"] = errorList[0].ErrorMessage;
        return new RedirectResult(Request.Headers["Referer"]);
      }

      PopulateManCoTextList(SearchViewModel);

      AddSearchViewModelToSession(SearchViewModel);

      var documentsViewModel = new DocumentsViewModel();

      PagedResult<IndexedDocumentData> documents = _documentService.GetDocuments(
        page,
        _pageSize,
        SearchViewModel.SelectedDocText,
        SearchViewModel.SelectedSubDocText,
        SearchViewModel.AddresseeSubType,
        SearchViewModel.AccountNumber,
        SearchViewModel.MailingName,
        SearchViewModel.ManCoTexts,
        SearchViewModel.InvestorReference,
        SearchViewModel.ProcessingDateFrom,
        SearchViewModel.ProcessingDateTo,
        SearchViewModel.PrimaryHolder,
        SearchViewModel.AgentReference,
        SearchViewModel.AddresseePostCode,
        SearchViewModel.EmailAddress,
        SearchViewModel.FaxNumber,
        SearchViewModel.ContractDate,
        SearchViewModel.PaymentDate,
        SearchViewModel.DocumentNumber);

      documentsViewModel.AddDocuments(documents);
      
      ProcessDocumentResults(documentsViewModel);

      TempData["valid"] = "Show filter";

      if (documents.Results.Count == 0 && documents.TotalItems > 0)
      {
        TempData["tooManyDocs"] = "There were too many documents returned from your search. Please refine your search criteria";
      }
      else
      {
        TempData["tooManyDocs"] = string.Empty;
      }

      if (isAjaxCall)
      {
        return PartialView("_PagedDocumentResults", documentsViewModel);
      }
      
      return View(documentsViewModel);
    }
    
    public ActionResult PdfContainer(string documentId)
    {
      return PartialView("_PdfContainer", documentId);
    }

    public ActionResult Status(string documentId)
    {
      var document = _documentService.GetDocument(documentId);

      if (document != null)
      {
        return PartialView("_DocumentStatus", new DocumentStatusViewModel(document));  
      }
      else
      {
        return PartialView("_DocumentStatus", new DocumentStatusViewModel());
      }
    }

    [OutputCache(CacheProfile = "medium", VaryByParam = "document")]
    private MemoryStream ConvertToStream(byte[] document)
    {
      MemoryStream memoryStream = new MemoryStream();
      memoryStream.Write(document, 0, document.Length);
      memoryStream.Position = 0;

      HttpContext.Response.AddHeader("content-disposition", "inline; filename=myPDF.pdf");
      return memoryStream;
    }

    private void AddSearchViewModelToSession(SearchViewModel searchViewModel)
    {
      this.HttpContext.Session["SearchViewModel"] = searchViewModel;
    }

    private void PopulateManCoTextList(SearchViewModel searchViewModel)
    {
      if (searchViewModel.SelectedManCoText == null)
      {
        searchViewModel.ManCoTexts = this.GenerateMancoTextList().ToList();
      }
      else
      {
        searchViewModel.ManCoTexts.Add(searchViewModel.SelectedManCoText.Trim());
      }  
    }

    private IList<string> GenerateMancoTextList()
    {
      var manCoTextList = new List<string>();

      var currentUser = this._userService.GetApplicationUser();
      var manCos = this._manCoService.GetManCosByUserId(currentUser.Id);

      manCos.ToList().ForEach(x => manCoTextList.Add(x.Code));

      return manCoTextList;
    }

    private void ProcessDocumentResults(DocumentsViewModel dvm)
    {
      foreach (DocumentViewModel documentViewModel in dvm.Documents)
      {
        Document document = _documentService.GetDocument(documentViewModel.DocumentId);
        documentViewModel.AddCheckoutDetails(document);
        documentViewModel.AddApprovalDetails(document);
        documentViewModel.AddRejectionDetails(document);
        documentViewModel.AddGridRunDetails(document);
        documentViewModel.AddManCoDetails(document);
        documentViewModel.AddDoNotPrintFlag(document);
      }
    }
  }
}

UnityWeb/Controllers/GridRunController.cs
namespace UnityWeb.Controllers
{
  using System.Collections.Generic;
  using System.Web.Mvc;
  using Entities;
  using Logging;
  using ServiceInterfaces;
  using UnityWeb.Filters;
  using UnityWeb.Models.Dashboard;
  using UnityWeb.Models.GridRun;

  [AuthorizeLoggedInUser]
  public class GridRunController : BaseController
  {
    private readonly IGridRunService _gridRunService;
    private readonly IUserService _userService;
    public int _pageSize = 10;

    public GridRunController(
        IGridRunService gridRunService,
        IUserService userService,
        ILogger logger)
      : base(logger)
    {
      _gridRunService = gridRunService;
      _userService = userService;
    }

    public ActionResult HouseHolding(string houseHoldingGrid, int page = 1)
    {
      var manCoFilterViewModel = new ManCoFilterViewModel();
      var manCos = new List<int>();
      var gridRunsViewModel = new GridRunsDetailViewModel();
      var gridRuns = new PagedResult<GridRun>();

      if (Session["ManCoFilter"] != null)
      {
        manCoFilterViewModel = (ManCoFilterViewModel)Session["ManCoFilter"];
        manCos.Add(int.Parse(manCoFilterViewModel.SelectedManCoId));
        gridRuns = _gridRunService.GetGridRuns(page, _pageSize, houseHoldingGrid, manCos);

        gridRunsViewModel.AddGridRuns(gridRuns, true);
        return View(gridRunsViewModel);
      }

      gridRuns = _gridRunService.GetGridRuns(page, _pageSize, houseHoldingGrid);
      gridRunsViewModel.AddGridRuns(gridRuns, true);
      return View(gridRunsViewModel);
    }

    public ActionResult Unapproved(int page = 1)
    {
      var manCoFilterViewModel  = new ManCoFilterViewModel();
      var manCos = new List<int>();
      var gridRunsViewModel = new GridRunsDetailViewModel();
      var gridRuns = new PagedResult<GridRun>();

      if (Session["ManCoFilter"] != null)
      {
        manCoFilterViewModel = (ManCoFilterViewModel)Session["ManCoFilter"];
        manCos.Add(int.Parse(manCoFilterViewModel.SelectedManCoId));
        gridRuns = _gridRunService.GetUnapproved(page, _pageSize, manCos);

        gridRunsViewModel.AddGridRuns(gridRuns);
        return View(gridRunsViewModel);
      }

      gridRuns = _gridRunService.GetUnapproved(page, _pageSize);
      gridRunsViewModel.AddGridRuns(gridRuns);
      return View(gridRunsViewModel);
    }

    [OutputCache(CacheProfile = "medium", VaryByParam = "grid")]
    public ActionResult Search(string grid)
    {
      var gridSearchesViewModel = new GridRunSearchesViewModel();
      var gridRuns = _gridRunService.Search(grid, this._userService.GetUserManCoIds());
      gridSearchesViewModel.AddGridRuns(gridRuns);
      return View(gridSearchesViewModel);
    }

    public ActionResult Status(int gridRunId)
    {
      var gridRun = _gridRunService.GetGridRun(gridRunId);
      return PartialView("_GridRunStatus", new GridRunStatusViewModel(gridRun));
    }
  }
}

UnityWeb/Views/Document/Search.cshtml
@using UnityWeb.HtmlHelpers
@using UnityWeb.Resources.Document
@using UnityWeb.Resources.Global
@model UnityWeb.Models.Document.DocumentsViewModel

@{
    ViewBag.Title = Search.Title;
}

<div id="addGRIDToCartUrl" data-request-url="@Url.Action("AddGridToCart", "CartItem")"></div>
<div id="addToCartUrl" data-request-url="@Url.Action("AddToCart", "CartItem")"></div>
<div id="showPDFUrl" data-request-url="@Url.Action("PdfContainer", "Document")"></div>
<div id="showDocumentStatusUrl" data-request-url="@Url.Action("Status", "Document")"></div>

<section class="hotsearch floatleft hotsearch2">
    <ul>
        <li>@Search.DataLevel</li>
        <li>@Search.GridLevel</li>
        <li class="last on">@Search.DocumentLevel</li>
    </ul>
</section>
<div class="clearfix"></div>
@{
    if (Model.GridSearch != null)
    {
        <p>@Search.Grid: @Model.GridSearch </p>
    }
}
<div id="documentData">
    @Html.Partial("_PagedDocumentResults", Model)
</div>
@Html.BeginDiv("Admin,dstadmin,Governor")
@Html.HiddenFor(m => Model.GridSearch, new { @class = "gridSearch" })
<div class="actionbtn">
    <ul class="actiondd">
        <li><a href="#" class="btndropdown">Actions</a>
            <ul>
              <li><a href="" id="addToCart">@Search.AddToBasket</a></li>
              <li><a href="" id="addGridToCart">@Search.AddGridToBasket</a></li>
                @{
                    if (Model.GridSearch != null) {
                        <li><a href="" id="approveGrid">@Search.ApproveGrid</a></li>
                    }
                }
                <li><a href="" id="approveSelected">@Search.ApproveDocument</a></li>
                @{
                    if (Model.GridSearch != null) {
                        <li><a href="" id="rejectGrid">@Search.RejectGrid</a></li>
                    }
                }
                <li><a href="" id="rejectSelected">@Global.RejectDocument</a></li>
            </ul>
        </li>
    </ul>
</div>
@Html.EndDiv()
<div class="clearfix"></div>

<!-- Modal -->
<div id="approveGridModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">@Search.ApproveGrid</h3>
  </div>
  <div class="modal-body">
    <p>@Search.ApproveGridMsg</p>
  </div>
  <div class="modal-footer">
    <button id="confirm" class="btn btn-primary">@Global.Confirm</button>
    <button id="cancel" class="btn" data-dismiss="modal" aria-hidden="true">@Global.Decline</button>
  </div>
</div>
<div id="approveSelectedModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">@Search.ApproveDocument</h3>
  </div>
  <div class="modal-body">
    <p>@Global.ApproveSelectedMsg</p>
  </div>
  <div class="modal-footer">
    <button id="confirmApproveSelected" class="btn btn-primary">@Global.Confirm</button>
    <button id="cancel" class="btn" data-dismiss="modal" aria-hidden="true">@Global.Decline</button>
  </div>
</div>
<div id="rejectGridModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">@Search.RejectGrid</h3>
  </div>
  <div class="modal-body">
    <p>@Search.RejectGridMsg</p>
  </div>
  <div class="modal-footer">
    <button id="confirm" class="btn btn-primary">@Global.Confirm</button>
    <button id="cancel" class="btn" data-dismiss="modal" aria-hidden="true">@Global.Decline</button>
  </div>
</div>
<div id="rejectSelectedModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">@Global.RejectDocument</h3>
  </div>
  <div class="modal-body">
    <p>@Global.RejectSelectedMsg</p>
  </div>
  <div class="modal-footer">
    <button id="confirmRejectSelected" class="btn btn-primary">@Global.Confirm</button>
    <button id="cancel" class="btn" data-dismiss="modal" aria-hidden="true">@Global.Decline</button>
  </div>
</div>
<div id="pleaseSelectModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">@Global.PleaseSelect</h3>
  </div>
  <div class="modal-body">
    <p>@Global.PleaseSelect</p>
  </div>
  <div class="modal-footer">
    <button id="continue" class="btn btn-primary">@Global.Continue</button>
  </div>
</div>
<div id="manCoConflictModal" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">@Global.CannotAdd</h3>
  </div>
  <div class="modal-body">
    <p>@Global.ManCoIssue</p>
  </div>
  <div class="modal-footer">
    <button id="continue" class="btn btn-primary">@Global.Continue</button>
  </div>
</div>

UnityWeb/Views/Document/_ShowSingleDocument.cshtml
@using UnityWeb.HtmlHelpers
@model List<UnityWeb.Models.Document.DocumentViewModel>
    
@for (int i = 0; i < Model.Count; i++)
  {
    var checkedRow = (@Model[i].CheckedOut ? "checkedRow" : "");
    
    <!--<tr>
      <td colspan="10">
        <table class="subtable">
          <thead>-->
            <tr class="data">
                <th class="@checkedRow" style="background:#ececec;">
                    @if (@Model[i].CheckedOut)
                    {
                    @Html.BeginDiv("Admin,dstadmin,Governor",new Dictionary<string, object>{ {"class","checkOutDocDiv checkOutImg"}, {"title", "Document checked out by " +  @Model[i].CheckedOutBy}  })
                    }
                    else
                    {
                    @Html.BeginDiv("Admin,dstadmin,Governor",new Dictionary<string, object>{{"class","checkOutDocDiv"}}) 
                    }
                
                    @Html.CheckBoxFor(m => m[i].Selected, new { @class = "docSelected" })

                    @Html.EndDiv()
                    @Html.HiddenFor(m => m[i].DocumentId, new { @class= "docId" })
                    @Html.HiddenFor(m => m[i].ManCoDisplay, new { @class = "manCoDisplay" })
                    @Html.HiddenFor(m => m[i].DocType, new { @class = "docType" })
                    @Html.HiddenFor(m => m[i].SubDocType, new { @class = "subDocType" })
                    @Html.HiddenFor(m => m[i].DocumentId, new { @class = "documentId" })
                  @Html.HiddenFor(m => m[i].ManCo, new { @class = "manCo" })
                </th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;"><img src="@Url.Content("~/Images/warning.png")" class="warning" style="display:none;" /> @Model[i].DocType</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].SubDocType</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].ManCoDisplay</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].AccountNumber</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].InvestorReference</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].MailPrintFlag</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].AddresseeSubType</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">@Model[i].ApprovalStatus</th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">
                @Html.ActionImage(@Url.Action("PdfContainer", "Document", new { DocumentId = Model[i].DocumentId }), @Url.Content("~/Images/pdf.gif"), "pdf", "showDocument") 
                @Html.HiddenFor(m => Model[i].DocumentId, new { @class= "DocumentId" })
              </th>
              <th class="odd @checkedRow txtcentre" style="background:#ececec;">
                @Html.ActionImage(@Url.Action("Status", "Document", new { DocumentId = Model[i].DocumentId }), @Url.Content("~/Images/progress.jpg"), "pdf", "showDocumentStatus") 
                @Html.HiddenFor(m => Model[i].DocumentId, new { @class= "DocumentId" })
              </th>
                <th class="odd @checkedRow txtcentre" style="background:#ececec;">
                @Html.ActionImage(@Url.Action("Search", "GridRun", new { Grid = Model[i].Grid }), @Url.Content("~/Images/gridsearch.jpg"), "pdf", "showGrid") 
                @Html.HiddenFor(m => Model[i].DocumentId, new { @class= "DocumentId" })
              </th> 
            </tr>
          <!--</thead>
        </table>
      </td>
    </tr>-->
  }
  