UnityWeb/Models/KpiReport/KpiReportDataViewModel.cs
namespace UnityWeb.Models.KpiReport
{
  public class KpiReportDataViewModel
  {
    public KpiReportDataViewModel(Entities.KpiReportData kpiData)
    {
      this.DocType = kpiData.DocType;
      this.SubDocType = kpiData.SubDocType;
      this.NumberOfDocs = kpiData.NumberOfDocs;
    }

    public string Id { get; set; }

    public string DocType { get; set; }

    public string SubDocType { get; set; }

    public int NumberOfDocs { get; set; }
  }
}

UnityWeb/Models/KpiReport/KpiReportViewModel.cs
namespace UnityWeb.Models.KpiReport
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  using UnityWeb.Models.ManCo;

  public class KpiReportViewModel : IValidatableObject
  {
    public string SelectedManCoId { get; set; }

    public DateTime? DateTo { get; set; }

    public DateTime? DateFrom { get; set; }

    private List<ManCoViewModel> _namCos = new List<ManCoViewModel>();

    public List<ManCoViewModel> ManCos
    {
      get
      {
        return _namCos;
      }
      set
      {
        _namCos = value;
      }
    }

    public void AddMancos(IList<Entities.ManCo> manCos)
    {
      foreach (Entities.ManCo manCo in manCos)
      {
        var mvm = new ManCoViewModel(manCo);
        mvm.AddDisplayName(manCos);
        ManCos.Add(mvm);
      }
    }

    public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
    {
      if (string.IsNullOrEmpty(SelectedManCoId))
      {
        yield return new ValidationResult("Please select a man co");
      }
      else if (!this.ValidateDateRange(DateFrom, DateTo))
      {
        yield return new ValidationResult("Please select a valid date range");
      }
    }

    private bool ValidateDateRange(DateTime? fromDate, DateTime? toDate)
    {
      if (fromDate == null || toDate == null)
      {
        return false;
      }
      else if (fromDate > toDate)
      {
        return false;
      }
      else if (fromDate > DateTime.Now)
      {
        return false;
      }
      else if (toDate > DateTime.Now)
      {
        return false;
      }
      else
      {
        return true;
      }
    }
  }
}

UnityWeb/Models/KpiReport/KpiReportsDataViewModel.cs
namespace UnityWeb.Models.KpiReport
{
  using System.Collections.Generic;
  using System.Linq;

  public class KpiReportsDataViewModel
  {
    public string ManCo { get; set; }

    public KpiReportViewModel KpiReportViewModel { get; set; }

    private List<KpiReportDataViewModel> _kpiReport = new List<KpiReportDataViewModel>();

    public KpiReportsDataViewModel(KpiReportViewModel kpiReportViewModel)
    {
      KpiReportViewModel = kpiReportViewModel;
    }

    public KpiReportsDataViewModel(IList<Entities.KpiReportData> kpiReportData, KpiReportViewModel kpiReportViewModel)
      : this(kpiReportViewModel)
    {
      if (kpiReportData.Count > 0)
      {
        ManCo = string.Format("{0} - {1}", kpiReportData.First().ManCo.Code, kpiReportData.First().ManCo.Description);
      }
    }

    public List<KpiReportDataViewModel> KpiReport
    {
      get { return this._kpiReport; }
      set { this._kpiReport = value; }
    }

    public void AddKpiData(IEnumerable<Entities.KpiReportData> kpiReportDatas)
    {
      foreach (var kpiReportData in kpiReportDatas)
      {
        var uvm = new KpiReportDataViewModel(kpiReportData);
        this.KpiReport.Add(uvm);
      }
    }
  }
}

UnityWeb/Controllers/KpiReportsController.cs
namespace UnityWeb.Controllers
{
  using System;
  using System.Collections.Generic;
  using System.Linq;
  using System.Text;
  using System.Web.Mvc;
  using Entities;
  using ServiceInterfaces;
  using UnityWeb.Filters;
  using Logging;
  using UnityWeb.Models.KpiReport;

  [AuthorizeLoggedInUser]
  public class KpiReportsController : BaseController
  {
    private readonly IDocumentService _documentService;
    private readonly IManCoService _manCoService;
    private readonly IUserService _userService;

    public KpiReportsController(IDocumentService documentService, IManCoService manCoService, IUserService userService, ILogger logger)
      : base(logger)
    {
      _documentService = documentService;
      _manCoService = manCoService;
      _userService = userService;
    }

    public ActionResult Index()
    {
      var model = new KpiReportViewModel();
      PopulateKpiViewModel(model);
      return this.View(model);
    }

    public ActionResult Run(string submitButton, KpiReportViewModel kpiReportViewModel)
    {
      this.PopulateKpiViewModel(kpiReportViewModel);

      if (!this.ModelState.IsValid)
      {
        var errorList = this.ModelState.Values.SelectMany(x => x.Errors).ToList();
        this.TempData["kpierror"] = errorList[0].ErrorMessage;

        return this.View("Index", kpiReportViewModel);
      }

      var documents = this._documentService.GetDocuments(Convert.ToInt32(kpiReportViewModel.SelectedManCoId), kpiReportViewModel.DateFrom.Value, kpiReportViewModel.DateTo.Value);

      switch (submitButton)
      {
        case "Run":
          return Show(kpiReportViewModel, documents);
        case "Export":
          string manco = string.Format("{0} - {1}", documents.First().ManCo.Code, documents.First().ManCo.Description);
          return Export(documents, manco, kpiReportViewModel.DateFrom.Value.ToShortDateString(), kpiReportViewModel.DateTo.Value.ToShortDateString());
        default:
          return (View());
      }
    }

    private ActionResult Show(KpiReportViewModel kpiReportViewModel, IList<KpiReportData> documents)
    {
      if (documents.Count == 0)
      {
        TempData["noData"] = "There were no documents found for your search criteria.";
        return this.View(new KpiReportsDataViewModel(kpiReportViewModel));
      }

      var kpiReportsDataViewModel = new KpiReportsDataViewModel(documents, kpiReportViewModel);
      kpiReportsDataViewModel.AddKpiData(documents);

      return this.View(kpiReportsDataViewModel);
    }

    private ActionResult Export(IEnumerable<KpiReportData> documents, string manCo, string startDate, string endDate)
    {
      var builder = GetKpiReport(documents, manCo, startDate, endDate);

      return File(new UTF8Encoding().GetBytes(builder.ToString()), "text/csv", string.Format("KPIReport_{0}.csv", DateTime.Now.ToShortTimeString()));
    }

    private void PopulateKpiViewModel(KpiReportViewModel kpiReportViewModel)
    {
      var currentUser = this._userService.GetApplicationUser();
      var manCos = this._manCoService.GetManCosByUserId(currentUser.Id);
      kpiReportViewModel.AddMancos(manCos);
    }

    private StringBuilder GetKpiReport(IEnumerable<KpiReportData> documents, string manCo, string startDate, string endDate)
    {
      var csvBuilder = new StringBuilder();

      csvBuilder.Append("MAN CO: " + manCo);
      csvBuilder.Append(",");

      csvBuilder.Append("START DATE: " + startDate);
      csvBuilder.Append(",");

      csvBuilder.Append("END DATE: " + endDate);
      csvBuilder.Append(",");

      csvBuilder.Append("\n");
      csvBuilder.Append("\n");

      csvBuilder.Append("DOC TYPE");
      csvBuilder.Append(",");

      csvBuilder.Append("SUB DOC ROLE");
      csvBuilder.Append(",");

      csvBuilder.Append("DOCUMENTS");
      csvBuilder.Append(",");

      csvBuilder.Append("\n");

      foreach (var document in documents)
      {
        csvBuilder.Append(document.DocType);
        csvBuilder.Append(",");

        csvBuilder.Append(document.SubDocType);
        csvBuilder.Append(",");

        csvBuilder.Append(document.NumberOfDocs);
        csvBuilder.Append(",");

        csvBuilder.Append("\n");
      }

      return csvBuilder;
    }
  }
}

UnityWeb/Views/KpiReports/Index.cshtml
@using UnityWeb.Resources.KpiReports
@model UnityWeb.Models.KpiReport.KpiReportViewModel

@{
  ViewBag.Title = KpiReports.Title;
}

<section>
  <h2 class="header">@KpiReports.Title</h2>
</section>

@using (Html.BeginForm("Run", "KpiReports", FormMethod.Post))
{
  @Html.Partial("_KpiSearch", Model)
}

UnityWeb/Views/KpiReports/Run.cshtml
@using UnityWeb.Models.KpiReport
@using UnityWeb.Resources.KpiReports
@model UnityWeb.Models.KpiReport.KpiReportsDataViewModel

@{
  ViewBag.Title = KpiReports.Title;
}

<section>
  <h2 class="header">@KpiReports.Title</h2>
</section>

@using (Html.BeginForm("Run", "KpiReports", FormMethod.Post))
{
  @Html.Partial("_KpiSearch", Model.KpiReportViewModel)
  <input type="submit" class="filterbtnReport"  title="Export" value="Export" name="submitButton" @{if (Model.KpiReport.Count() == 0)
                                                                                               {
                                                                                                 @:disabled="disabled"
                                                                                               } } />
}

<section>
  <br />
  <br />
  <h3>@Model.ManCo</h3>
  <section class="accordion">
    <section class="pane">
      <table>
        <thead>
          <tr>
            <th class="data5">DOC TYPE</th>
            <th class="data4">SUB DOC TYPE</th>
            <th class="data5">DOCUMENTS</th>
            <th class="last"></th>
          </tr>
        </thead>
        <tbody>
          @foreach (KpiReportDataViewModel piReportDataViewModel in Model.KpiReport)
          {
            <tr>
              <td colspan="6">
                <table class="subtable">
                  <thead>
                    <tr>
                      <th class="data5 odd">@piReportDataViewModel.DocType</th>
                      <th class="data4 odd">@piReportDataViewModel.SubDocType</th>
                      <th class="data5 odd">@piReportDataViewModel.NumberOfDocs</th>
                      <th class="last"></th>
                    </tr>
                  </thead>
                </table>
              </td>
            </tr>
          }
        </tbody>
      </table>
    </section>
  </section>
</section>
<span id="searchDocError">@TempData["noData"] </span>
<div class="clearfix"></div>

UnityWeb/Views/KpiReports/_KpiSearch.cshtml
@model UnityWeb.Models.KpiReport.KpiReportViewModel

<div class="kpiReport">
    <div class="col5 floatleft noclear marginright15">
      <div class="ddl">
        @Html.DropDownListFor(x => x.SelectedManCoId, new SelectList(Model.ManCos, "Id", "DisplayName"), "MAN CO")
      </div>
    </div>
    <div class="col2pt4 floatleft noclear marginright12">
      <div>
        @Html.TextBox("DateFrom", Model.DateFrom != null ? Model.DateFrom.Value.ToString("d") : null, new { data_datepicker = true, @class = "filtertxt2", @placeholder = "Date From" })
      </div>
    </div>
    <div class="col2pt4 floatleft noclear marginright12">
      <div>
        @Html.TextBox("DateTo", Model.DateTo != null ? Model.DateTo.Value.ToString("d") : null, new { data_datepicker = true, @class = "filtertxt2", @placeholder = "Date To" })
      </div>
    </div>
    <div class="clearfix"></div>
    <hr>
    <div class="floatleft">
       <span id="kpiError" class="kpierror">@TempData["kpierror"]</span>
    </div>
    <div class="floatright">
      <input type="submit" class="floatright filterbtnReport txtcentre" value="Run" name="submitButton" />
    </div>
    <div class="clearfix"></div>
</div>